##
## Build Stage
##

FROM golang:latest as build

ENV GOOS=linux \
    GOARCH=amd64 \
    GO111MODULE=on \
    CGO_ENABLED=1 \
    ENABLE_PPROF=true

WORKDIR /workspace

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /workspace/rsa ./cmd/main.go

ENTRYPOINT ["./rsa"]
